# Membuat Matriks dengan NumPy

In [ ]:
import numpy as np

In [ ]:
#  Definisi Matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]


# Operasi Dasar Matriks

In [ ]:
# Penjumlahan dan Pengurangan
print(f"Matriks A + Matriks B:\n{A + B}")
print(f"Matriks A - Matriks B:\n{A - B}")

# Perkalian Skalar
print(f"2 x Matriks A:\n{2 * A}")
print(f"Matriks A x Matriks B:\n{A * B}")

Matriks A + Matriks B:
[[ 6  8]
 [10 12]]
Matriks A - Matriks B:
[[-4 -4]
 [-4 -4]]
2 x Matriks A:
[[2 4]
 [6 8]]
Matriks A x Matriks B:
[[ 5 12]
 [21 32]]


# Perkalian Matriks (DotProduct)

In [ ]:
# Perkalian Matrix
C = np.dot(A,B)
D = A @ B
print(f"A x B:\n{C}")
print(f"A x B:\n{D}")

A x B:
[[19 22]
 [43 50]]
A x B:
[[19 22]
 [43 50]]


# Transpose Matriks

In [ ]:
# Transpose Matriks
print("Matriks A Sebelum Transpose:\n",A)
print(f"Transpose Matriks A:\n{A.T}")
print("Matriks B Sebelum Transpose:\n",B)
print(f"Transpose Matriks B:\n{B.T}")

# Coba Matriks 1 x 2
Non_Persegi = np.array([[1,2]])
print("Transpose Matrix Non-persegi:\n",Non_Persegi)

Matriks A Sebelum Transpose:
 [[1 2]
 [3 4]]
Transpose Matriks A:
[[1 3]
 [2 4]]
Matriks B Sebelum Transpose:
 [[5 6]
 [7 8]]
Transpose Matriks B:
[[5 7]
 [6 8]]
Transpose Matrix Non-persegi:
 [[1 2]]


# Invers Matriks

In [ ]:
# Inverse Matriks
A_Inv = np.linalg.inv(A)
print("Matriks A sebelum inverse:\n",A)
print("Inverse Matriks A:\n",A_Inv)
# Uji coba dengan matriks B
B_Inv = np.linalg.inv(B)
print("Matriks B sebelum inverse:\n",B)
print("Inverse Matriks B:\n",B_Inv)

Matriks A sebelum inverse:
 [[1 2]
 [3 4]]
Inverse Matriks A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matriks B sebelum inverse:
 [[5 6]
 [7 8]]
Inverse Matriks B:
 [[-4.   3. ]
 [ 3.5 -2.5]]


# Membuat penyelesaian Sistem Persamaan Linier:
# $$
\mathbf{A}\mathbf{x} = \mathbf{b}
$$
di mana:

𝐴 adalah matriks koefisien berukuran
𝑚 × 𝑛(biasanya square matrix
𝑛 × 𝑛 jika ada solusi unik),

𝑥 adalah vektor variabel yang ingin kita cari,

b adalah vektor hasil.
# Dengan Menggunakan NumPy

In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Matriks A (Koefisien)
A = np.array([[2, 1], [1, -1]])

# Vektor b (Hasil)
b = np.array([1, 3])

# Menyelesaikan untuk x
x = np.linalg.solve(A, b)

print("Solusi untuk x dan y:\n", x)

Solusi untuk x dan y:
 [ 1.33333333 -1.66666667]


## Misalkan kita punya sistem persamaan<br>
# $
\begin{cases} 3x + 2y = 5 \\ 4x - y = 6 \end{cases}
$
## Maka bentuk matriks nya
# $
\begin{bmatrix} 3 & 2 \\ 4 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 5 \\ 6 \end{bmatrix}
$


## Dengan Fungsi np.linalg.solve(A, b) secara matematis menyelesaikan
# $
\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}
$
## Namun, NumPy tidak benar-benar menghitung invers matriks, karena itu tidak efisien. Sebagai gantinya, NumPy menggunakan metode Gaussian Elimination yang lebih cepat.

In [ ]:
import numpy as np

A = np.array([[3, 2], [4, -1]])  # Matriks Koefisien
b = np.array([5, 6])             # Vektor Hasil

X = np.linalg.solve(A, b)  # Cari solusi untuk x dan y

print("Solusi untuk x dan y:", X)

Solusi untuk x dan y: [1.54545455 0.18181818]
